### ISSUE TITLE
Locality Support

### ISSUE THREAD

**Issue by PatrickTulskie** [PatrickTulskie/hocus_focus#2]
As reported by @solidfox, the extension doesn't work correctly if your search engine isn't in the following regex: `/google\.com|bing\.com|yahoo\.com/`

I have to investigate the current Safari API but it might be possible to find out what the user's currently selected search engine is and just match based on that instead of an all encompassing regex.  Barring that, it might make sense to let the user specify what URL(s) they want to match on.

I'm open to suggestions on how to solve this in a performant manner.  I just want to make sure this isn't significantly slowing down new page loads for everyone.

**Comment by solidfox** [comment]
How about (google|yahoo|bing)/.[a-z][a-z]

/Daniel Schlaug

**Comment by PatrickTulskie** [comment]
Closing this out since uh Safari extensions like this aren't really a thing anymore :(
